import { Request, Response } from "express";
import { User } from "../auth/user.model";
import Stripe from "stripe";
import { subscriptionsModel } from "./subscriptions.model";
import { config } from "../../config";



const stripe = new Stripe(config.STRIPE_SECRET_KEY as string);
export const createSubscription = async (req: Request, res: Response) => {
  try {
    const { userID, priceId, planName } = req.body;

    if (!userID || !priceId || !planName) {
      return res.status(400).json({ message: "Missing required fields" });
    }

    const user = await User.findById(userID);
    if (!user) return res.status(404).json({ message: "User not found" });

    // 1️⃣ Stripe Customer Create
    const customer = await stripe.customers.create({
      email: user.email,
    });

    // 2️⃣ Stripe Subscription Create
    const subscription = await stripe.subscriptions.create({
      customer: customer.id,
      items: [{ price: priceId }],
      payment_behavior: "default_incomplete",
      expand: ["latest_invoice.payment_intent"],
    }) as any;

    // 3️⃣ Safe Handling for latest_invoice
    if (!subscription.latest_invoice) {
      return res.status(400).json({
        message: "No invoice generated by Stripe",
      });
    }

    const invoice = subscription.latest_invoice as any;

    if (!invoice.payment_intent) {
      return res.status(400).json({
        message: "No payment intent returned by Stripe",
      });
    }

    const paymentIntent = invoice.payment_intent;

    // 4️⃣ Save Data to Database
    await subscriptionsModel.create({
      userID,
      stripeCustomerId: customer.id,
      stripeSubscriptionId: subscription.id,
      stripePriceId: priceId,
      planName,
      amount: paymentIntent.amount,
      interval: "month",
      status: subscription.status,
      currentPeriodStart: subscription.current_period_start,
      currentPeriodEnd: subscription.current_period_end,
    });

    // 5️⃣ Send Client Secret to Frontend
    res.json({
      message: "Subscription created successfully",
      clientSecret: paymentIntent.client_secret,
      subscriptionId: subscription.id,
    });

  } catch (error: any) {
    console.error("Stripe Subscription Error:", error);
    res.status(500).json({ message: "Stripe Error", error: error.message });
  }
};






export const stripeWebhook = async (req: Request, res: Response) => {
  let event = req.body;

  try {
    switch (event.type) {
      case "invoice.payment_succeeded":
        const invoice = event.data.object;

        await subscriptionsModel.findOneAndUpdate(
          { stripeSubscriptionId: invoice.subscription },
          { status: "active" }
        );

        break;

      case "customer.subscription.deleted":
        await subscriptionsModel.findOneAndUpdate(
          { stripeSubscriptionId: event.data.object.id },
          { status: "canceled" }
        );
        break;
    }

    res.json({ received: true });

  } catch (err: any) {
    res.status(400).send(`Webhook error: ${err.message}`);
  }
};